# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MorphingGUI.ui'
#
# Created: Sun Apr 15 22:07:47 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 696)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadStartButton = QtGui.QPushButton(self.centralwidget)
        self.loadStartButton.setGeometry(QtCore.QRect(20, 10, 161, 27))
        self.loadStartButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loadStartButton.setObjectName("loadStartButton")
        self.loadEndButton = QtGui.QPushButton(self.centralwidget)
        self.loadEndButton.setGeometry(QtCore.QRect(510, 10, 161, 27))
        self.loadEndButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.loadEndButton.setObjectName("loadEndButton")
        self.trianglesCheckBox = QtGui.QCheckBox(self.centralwidget)
        self.trianglesCheckBox.setGeometry(QtCore.QRect(360, 290, 131, 22))
        self.trianglesCheckBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.trianglesCheckBox.setObjectName("trianglesCheckBox")
        self.alphaSlider = QtGui.QSlider(self.centralwidget)
        self.alphaSlider.setGeometry(QtCore.QRect(80, 320, 681, 20))
        self.alphaSlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.alphaSlider.setMaximum(100)
        self.alphaSlider.setSingleStep(5)
        self.alphaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.alphaSlider.setTickInterval(5)
        self.alphaSlider.setObjectName("alphaSlider")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 290, 111, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(620, 290, 111, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 610, 121, 20))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.blendButton = QtGui.QPushButton(self.centralwidget)
        self.blendButton.setGeometry(QtCore.QRect(360, 640, 141, 27))
        self.blendButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.blendButton.setObjectName("blendButton")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(80, 340, 21, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(740, 340, 21, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 320, 41, 20))
        self.label_6.setObjectName("label_6")
        self.alphaValueText = QtGui.QLineEdit(self.centralwidget)
        self.alphaValueText.setGeometry(QtCore.QRect(780, 320, 41, 27))
        self.alphaValueText.setFocusPolicy(QtCore.Qt.NoFocus)
        self.alphaValueText.setText("")
        self.alphaValueText.setAlignment(QtCore.Qt.AlignCenter)
        self.alphaValueText.setReadOnly(True)
        self.alphaValueText.setObjectName("alphaValueText")
        self.startingImage = QtGui.QGraphicsView(self.centralwidget)
        self.startingImage.setGeometry(QtCore.QRect(20, 50, 321, 231))
        self.startingImage.setObjectName("startingImage")
        self.endImage = QtGui.QGraphicsView(self.centralwidget)
        self.endImage.setGeometry(QtCore.QRect(510, 50, 321, 231))
        self.endImage.setObjectName("endImage")
        self.blendImage = QtGui.QGraphicsView(self.centralwidget)
        self.blendImage.setGeometry(QtCore.QRect(270, 370, 321, 231))
        self.blendImage.setObjectName("blendImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.loadStartButton.setText(QtGui.QApplication.translate("MainWindow", "Load Starting Image ...", None, QtGui.QApplication.UnicodeUTF8))
        self.loadEndButton.setText(QtGui.QApplication.translate("MainWindow", "Load Ending Image ...", None, QtGui.QApplication.UnicodeUTF8))
        self.trianglesCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Show Triangles", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Starting Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Ending Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Blending Result", None, QtGui.QApplication.UnicodeUTF8))
        self.blendButton.setText(QtGui.QApplication.translate("MainWindow", "Blend", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "0.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Alpha", None, QtGui.QApplication.UnicodeUTF8))

